version: '3'

vars:
  LANG: en
  VERBOSE: -v
  MIN_COVERAGE: 60
  GOLANGCI_VERSION: 1.51.2
  SRCS: ./**/*.go
  OUTDIR: out
  BIN: '{{.OUTDIR}}/firemage'
  COVER: '{{.OUTDIR}}/coverage.out'
  COVERHTML: '{{.OUTDIR}}/cov.html'
  LOG: '{{.PWD}}/{{.OUTDIR}}/log.txt'
  KEY: '{{.PWD}}/{{.OUTDIR}}/service-account.json'
  CONF: '{{.PWD}}/conf.yml'

includes:
  _os:
    taskfile: taskfiles/os_{{OS}}.yml
    internal: true
    dir: .

tasks:
  default:
    desc: Shows a help menu with all available commands and their descriptions.
    cmd: task -l

  help:
    desc: Helps with app commands.
    dir: cmd/firemage
    cmd: go run . -h

  setlang:
    desc: Sets language by symlinking internalization.
    requires:
      vars:
        - name: LANG
          enum: [hu, en]
    cmds: # TODO: how should we handle windows?
      - ln -sf ../../i18n/"{{.LANG}}"/lang.txt internal/lang/lang.go
      - ln -sf ./i18n/"{{.LANG}}"/conf.yml ./

  outDir:
    internal: true
    generates:
      - '{{.OUTDIR}}'
    status:
      - test -f {{.OUTDIR}}

  deps:
    internal: true
    sources:
      - go.mod
      - go.sum
    cmds:
      - go get ./...
      - go mod tidy

  install:
    desc: Install into current system.
    deps: [deps]
    cmd: go install ./cmd/firemage

  install-if-missing:
    internal: true
    silent: true
    sources:
      - '{{.SRCS}}'
    status:
      - command -v firemage >/dev/null 2>&1
    cmd:
      task: install

  run:
    desc: Runs the code.
    deps: [install-if-missing, outDir]
    cmd: firemage -k {{.KEY}} -c {{.CONF}} -l {{.LOG}} {{.CLI_ARGS}}

  debug:
    desc: Debug the app with helpful information
    deps: [deps, outDir]
    cmd: go run ./cmd/firemage -k {{.KEY}} -c {{.CONF}} {{.VERBOSE}} -l {{.LOG}} {{.CLI_ARGS}}

  do-build:
    internal: true
    deps: [deps, outDir]
    vars:
      GOARCH: '{{.ARCH | default "amd64"}}'
    cmd: GOOS={{.GOOS}} GOARCH={{.GOARCH}} go build -o {{.BIN}}{{.SUFFIX}} ./cmd
    sources:
      - '{{.SRCS}}'
    generates:
      - '{{.BIN}}{{.SUFFIX}}'

  build-linux:
    desc: (Cross-platform) linux build.
    cmd:
      task: do-build
      vars:
        GOOS: linux

  build-darwin:
    desc: (Cross-platform) mac build
    cmd:
      task: do-build
      vars:
        GOOS: darwin

  build-windows:
    desc: (Cross-platform) windows build
    cmd:
      task: do-build
      vars:
        GOOS: windows
        SUFFIX: '.exe'

  build:
    cmds:
      - cmd: echo windows
        platforms: [windows]
      - cmd: echo linux
        platforms: [linux]
      - cmd: echo darwin
        platforms: [darwin]
      - cmd: task build-windows
        platforms: [windows]
      - cmd: task build-linux
        platforms: [linux]
      - cmd: task build-darwin
        platforms: [darwin]

  golanci-lint:
    internal: true
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | bash -s -- -b .bin v{{.GOLANGCI_VERSION}}
      - mv .bin/golangci-lint .bin/golangci-lint-{{.GOLANGCI_VERSION}}
    generates:
      - .bin/golangci-lint-{{.GOLANGCI_VERSION}}
    status:
      - test -f .bin/golangci-lint-{{.GOLANGCI_VERSION}}

  lint:
    desc: Runs linter on the code.
    deps: [golanci-lint]
    cmd: .bin/golangci-lint-{{.GOLANGCI_VERSION}} run --skip-dirs "i18n|custom"

  test:
    desc: Executes Go tests with coverage for all packages.
    silent: true
    cmd: |
          GOLIST=$(go list ./...)
          for exclude in '.*/mock' './cmd' './out'; do
            GOLIST=$(echo "$GOLIST" | grep -v "$exclude")
          done
          echo "list: $GOLIST"
          go test -cover $GOLIST -timeout 60s {{.SUFFIX}}

  cover:
    desc: Generates test coverage report by its changes from origin/main.
    deps: [outDir]
    cmds:
      - task: test
        vars:
          SUFFIX: '-coverprofile={{.COVER}}'
      - go tool cover -o {{.COVERHTML}} -html={{.COVER}}
      - go tool cover -func={{.COVER}} | rg total
      - task: _os:sed
        vars:
          FROM: black
          TO: whitesmoke
          FILE: '{{.COVERHTML}}'
      - task: _os:browser
        vars:
          TARGET: '{{.COVERHTML}}'

  generate:
    desc: Runs the "go generate" command in the current directory and all subdirectories to generate code.
    cmds:
      - cmd: echo "Running go generate..."
        silent: true
      - go generate ./...
