version: '3'

vars:
  LANG: en
  KEY: service-account.json
  CONF: conf.yaml
  VERBOSE: -v
  MIN_COVERAGE: 60
  GOLANGCI_VERSION: 1.51.2


tasks:
  default:
    desc: Shows a help menu with all available commands and their descriptions.
    cmd: task -l

  help:
    desc: Helps with app commands.
    cmd: go run . -h

  setlang:
    desc: Sets language.
    requires:
      vars:
        - name: LANG
          enum: [hu, en]
    cmds: # TODO: how should we handle windows?
      - ln -sf ../i18n/"{{.LANG}}"/lang.go internal/
      - ln -sf i18n/"{{.LANG}}"/conf.yaml ./

  deps:
    internal: true
    cmd: go get ./internal/...

  golanci-lint:
    internal: true
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | bash -s -- -b .bin v{{.GOLANGCI_VERSION}}
      - mv .bin/golangci-lint .bin/golangci-lint-{{.GOLANGCI_VERSION}}
    generates:
      - .bin/golangci-lint-{{.GOLANGCI_VERSION}}
    status:
      - test -f .bin/golangci-lint-{{.GOLANGCI_VERSION}}

  lint:
    desc: Runs linter on the code.
    deps: [golanci-lint]
    cmd: .bin/golangci-lint-{{.GOLANGCI_VERSION}} run --skip-dirs "i18n|custom"

  build-lin:
    internal: true
    deps: [deps]
    cmd: GOOS=linux GOARCH=amd64 go out -o out/firemage .
    sources:
      - ./**/*.go
    generates:
      - out/firemage

  build-osx:
    internal: true
    deps: [deps]
    cmd: GOOS=darwin GOARCH=amd64 go out -o out/firemage .
    sources:
      - ./**/*.go
    generates:
      - out/firemage.exe

  build-win:
    internal: true
    deps: [deps]
    cmd: GOOS=windows GOARCH=amd64 go out -o out/firemage.exe .
    sources:
      - ./**/*.go
    generates:
      - out/firemage.exe

  build:
    deps: [deps]
    cmds:
      - cmd: go build -o out/firemage .
        platforms: [linux, darwin]
        generates:
          - out/firemage
      - cmd: go build -o out/firemage.exe .
        platforms: [windows]
        generates:
          - out/firemage.exe

  debug:
    deps: [deps]
    cmd: go run . -k {{.KEY}} -c {{.CONF}} {{.VERBOSE}} {{.CLI_ARGS}}

  install:
    deps: [deps]
    cmd: go install .

  run:
    desc: Runs the code.
    deps: [install]
    cmd: firemage -k {{.KEY}} -c {{.CONF}} {{.VERBOSE}} {{.CLI_ARGS}}

  test:
    desc: Tests the code.
    deps: [deps]
    cmds:
      - echo "testing ..."
      - go test -coverprofile coverage.out ./internal/... -v -p 1

  cover:
    desc: Checks code coverage, and opens the result in chromium with light colorscheme.
    cmd: go tool cover -o cov.html -html=coverage.out; sed -i 's/black/whitesmoke/g' cov.html; chromium cov.html
