// Code generated by MockGen. DO NOT EDIT.
// Source: ./firebase.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=./firebase.go -destination=../mock/mock_firebase.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	firestore "cloud.google.com/go/firestore"
	auth "firebase.google.com/go/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockFbIf is a mock of FbIf interface.
type MockFbIf struct {
	ctrl     *gomock.Controller
	recorder *MockFbIfMockRecorder
	isgomock struct{}
}

// MockFbIfMockRecorder is the mock recorder for MockFbIf.
type MockFbIfMockRecorder struct {
	mock *MockFbIf
}

// NewMockFbIf creates a new mock instance.
func NewMockFbIf(ctrl *gomock.Controller) *MockFbIf {
	mock := &MockFbIf{ctrl: ctrl}
	mock.recorder = &MockFbIfMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFbIf) EXPECT() *MockFbIfMockRecorder {
	return m.recorder
}

// DoList mocks base method.
func (m *MockFbIf) DoList() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoList")
	ret0, _ := ret[0].(error)
	return ret0
}

// DoList indicates an expected call of DoList.
func (mr *MockFbIfMockRecorder) DoList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoList", reflect.TypeOf((*MockFbIf)(nil).DoList))
}

// GetSpecs mocks base method.
func (m *MockFbIf) GetSpecs(ctx context.Context) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpecs", ctx)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpecs indicates an expected call of GetSpecs.
func (mr *MockFbIfMockRecorder) GetSpecs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpecs", reflect.TypeOf((*MockFbIf)(nil).GetSpecs), ctx)
}

// GetUsers mocks base method.
func (m *MockFbIf) GetUsers(ctx context.Context, uids []auth.UserIdentifier) (*auth.GetUsersResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx, uids)
	ret0, _ := ret[0].(*auth.GetUsersResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockFbIfMockRecorder) GetUsers(ctx, uids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockFbIf)(nil).GetUsers), ctx, uids)
}

// IterUsers mocks base method.
func (m *MockFbIf) IterUsers(cb func(*auth.UserRecord) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IterUsers", cb)
	ret0, _ := ret[0].(error)
	return ret0
}

// IterUsers indicates an expected call of IterUsers.
func (mr *MockFbIfMockRecorder) IterUsers(cb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IterUsers", reflect.TypeOf((*MockFbIf)(nil).IterUsers), cb)
}

// RunTransaction mocks base method.
func (m *MockFbIf) RunTransaction(ctx context.Context, cb func(*firestore.Transaction, map[string]any) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTransaction", ctx, cb)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunTransaction indicates an expected call of RunTransaction.
func (mr *MockFbIfMockRecorder) RunTransaction(ctx, cb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTransaction", reflect.TypeOf((*MockFbIf)(nil).RunTransaction), ctx, cb)
}

// Search mocks base method.
func (m *MockFbIf) Search(ctx context.Context, key, value string, cb func(string) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, key, value, cb)
	ret0, _ := ret[0].(error)
	return ret0
}

// Search indicates an expected call of Search.
func (mr *MockFbIfMockRecorder) Search(ctx, key, value, cb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockFbIf)(nil).Search), ctx, key, value, cb)
}

// StoreAuthClaims mocks base method.
func (m *MockFbIf) StoreAuthClaims(ctx context.Context, uid string, newClaims map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreAuthClaims", ctx, uid, newClaims)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreAuthClaims indicates an expected call of StoreAuthClaims.
func (mr *MockFbIfMockRecorder) StoreAuthClaims(ctx, uid, newClaims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreAuthClaims", reflect.TypeOf((*MockFbIf)(nil).StoreAuthClaims), ctx, uid, newClaims)
}

// UpdateSpecs mocks base method.
func (m *MockFbIf) UpdateSpecs(tr *firestore.Transaction, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSpecs", tr, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSpecs indicates an expected call of UpdateSpecs.
func (mr *MockFbIfMockRecorder) UpdateSpecs(tr, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSpecs", reflect.TypeOf((*MockFbIf)(nil).UpdateSpecs), tr, updates)
}
