// Code generated by MockGen. DO NOT EDIT.
// Source: ./frontend.go
//
// Generated by this command:
//
//	mockgen -package=mock -source=./frontend.go -destination=../mock/mock_frontend.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	common "github.com/vendelin8/firemage/internal/common"
	tview "github.com/vendelin8/tview"
	gomock "go.uber.org/mock/gomock"
)

// MockFeIf is a mock of FeIf interface.
type MockFeIf struct {
	ctrl     *gomock.Controller
	recorder *MockFeIfMockRecorder
	isgomock struct{}
}

// MockFeIfMockRecorder is the mock recorder for MockFeIf.
type MockFeIfMockRecorder struct {
	mock *MockFeIf
}

// NewMockFeIf creates a new mock instance.
func NewMockFeIf(ctrl *gomock.Controller) *MockFeIf {
	mock := &MockFeIf{ctrl: ctrl}
	mock.recorder = &MockFeIfMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeIf) EXPECT() *MockFeIfMockRecorder {
	return m.recorder
}

// ClaimButtonSetDisabled mocks base method.
func (m *MockFeIf) ClaimButtonSetDisabled(index int, isDisabled bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClaimButtonSetDisabled", index, isDisabled)
}

// ClaimButtonSetDisabled indicates an expected call of ClaimButtonSetDisabled.
func (mr *MockFeIfMockRecorder) ClaimButtonSetDisabled(index, isDisabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimButtonSetDisabled", reflect.TypeOf((*MockFeIf)(nil).ClaimButtonSetDisabled), index, isDisabled)
}

// ClaimsBtns mocks base method.
func (m *MockFeIf) ClaimsBtns(arg0 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClaimsBtns", arg0)
}

// ClaimsBtns indicates an expected call of ClaimsBtns.
func (mr *MockFeIfMockRecorder) ClaimsBtns(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimsBtns", reflect.TypeOf((*MockFeIf)(nil).ClaimsBtns), arg0)
}

// ClaimsDate mocks base method.
func (m *MockFeIf) ClaimsDate() *time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimsDate")
	ret0, _ := ret[0].(*time.Time)
	return ret0
}

// ClaimsDate indicates an expected call of ClaimsDate.
func (mr *MockFeIfMockRecorder) ClaimsDate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimsDate", reflect.TypeOf((*MockFeIf)(nil).ClaimsDate))
}

// ClaimsDateSetDisabled mocks base method.
func (m *MockFeIf) ClaimsDateSetDisabled(arg0 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClaimsDateSetDisabled", arg0)
}

// ClaimsDateSetDisabled indicates an expected call of ClaimsDateSetDisabled.
func (mr *MockFeIfMockRecorder) ClaimsDateSetDisabled(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimsDateSetDisabled", reflect.TypeOf((*MockFeIf)(nil).ClaimsDateSetDisabled), arg0)
}

// ClaimsSetDate mocks base method.
func (m *MockFeIf) ClaimsSetDate(arg0 time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClaimsSetDate", arg0)
}

// ClaimsSetDate indicates an expected call of ClaimsSetDate.
func (mr *MockFeIfMockRecorder) ClaimsSetDate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimsSetDate", reflect.TypeOf((*MockFeIf)(nil).ClaimsSetDate), arg0)
}

// CreateClaimChoser mocks base method.
func (m *MockFeIf) CreateClaimChoser() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateClaimChoser")
}

// CreateClaimChoser indicates an expected call of CreateClaimChoser.
func (mr *MockFeIfMockRecorder) CreateClaimChoser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClaimChoser", reflect.TypeOf((*MockFeIf)(nil).CreateClaimChoser))
}

// CurrentPage mocks base method.
func (m *MockFeIf) CurrentPage() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentPage")
	ret0, _ := ret[0].(string)
	return ret0
}

// CurrentPage indicates an expected call of CurrentPage.
func (mr *MockFeIfMockRecorder) CurrentPage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentPage", reflect.TypeOf((*MockFeIf)(nil).CurrentPage))
}

// HidePopup mocks base method.
func (m *MockFeIf) HidePopup(popup string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HidePopup", popup)
}

// HidePopup indicates an expected call of HidePopup.
func (mr *MockFeIfMockRecorder) HidePopup(popup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HidePopup", reflect.TypeOf((*MockFeIf)(nil).HidePopup), popup)
}

// LayoutUsers mocks base method.
func (m *MockFeIf) LayoutUsers() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LayoutUsers")
}

// LayoutUsers indicates an expected call of LayoutUsers.
func (mr *MockFeIfMockRecorder) LayoutUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LayoutUsers", reflect.TypeOf((*MockFeIf)(nil).LayoutUsers))
}

// Quit mocks base method.
func (m *MockFeIf) Quit() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Quit")
}

// Quit indicates an expected call of Quit.
func (mr *MockFeIfMockRecorder) Quit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quit", reflect.TypeOf((*MockFeIf)(nil).Quit))
}

// ReplaceTableItem mocks base method.
func (m *MockFeIf) ReplaceTableItem(i int, key string, p tview.Primitive) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReplaceTableItem", i, key, p)
}

// ReplaceTableItem indicates an expected call of ReplaceTableItem.
func (mr *MockFeIfMockRecorder) ReplaceTableItem(i, key, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceTableItem", reflect.TypeOf((*MockFeIf)(nil).ReplaceTableItem), i, key, p)
}

// Run mocks base method.
func (m *MockFeIf) Run() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run")
}

// Run indicates an expected call of Run.
func (mr *MockFeIfMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockFeIf)(nil).Run))
}

// SetOnShow mocks base method.
func (m *MockFeIf) SetOnShow(arg0 string, arg1 func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOnShow", arg0, arg1)
}

// SetOnShow indicates an expected call of SetOnShow.
func (mr *MockFeIfMockRecorder) SetOnShow(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOnShow", reflect.TypeOf((*MockFeIf)(nil).SetOnShow), arg0, arg1)
}

// SetPage mocks base method.
func (m *MockFeIf) SetPage(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPage", arg0)
}

// SetPage indicates an expected call of SetPage.
func (mr *MockFeIfMockRecorder) SetPage(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPage", reflect.TypeOf((*MockFeIf)(nil).SetPage), arg0)
}

// ShowClaimChoser mocks base method.
func (m *MockFeIf) ShowClaimChoser(i int, key string, c common.Claim) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowClaimChoser", i, key, c)
}

// ShowClaimChoser indicates an expected call of ShowClaimChoser.
func (mr *MockFeIfMockRecorder) ShowClaimChoser(i, key, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowClaimChoser", reflect.TypeOf((*MockFeIf)(nil).ShowClaimChoser), i, key, c)
}

// ShowConfirm mocks base method.
func (m *MockFeIf) ShowConfirm(onYes, onNo func(), ms ...string) {
	m.ctrl.T.Helper()
	varargs := []any{onYes, onNo}
	for _, a := range ms {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ShowConfirm", varargs...)
}

// ShowConfirm indicates an expected call of ShowConfirm.
func (mr *MockFeIfMockRecorder) ShowConfirm(onYes, onNo any, ms ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{onYes, onNo}, ms...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowConfirm", reflect.TypeOf((*MockFeIf)(nil).ShowConfirm), varargs...)
}

// ShowMsg mocks base method.
func (m *MockFeIf) ShowMsg(ms ...string) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range ms {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ShowMsg", varargs...)
}

// ShowMsg indicates an expected call of ShowMsg.
func (mr *MockFeIfMockRecorder) ShowMsg(ms ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowMsg", reflect.TypeOf((*MockFeIf)(nil).ShowMsg), ms...)
}

// ShowProgress mocks base method.
func (m *MockFeIf) ShowProgress(ctx context.Context, cancelFunc context.CancelFunc, ms ...string) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, cancelFunc}
	for _, a := range ms {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ShowProgress", varargs...)
}

// ShowProgress indicates an expected call of ShowProgress.
func (mr *MockFeIfMockRecorder) ShowProgress(ctx, cancelFunc any, ms ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, cancelFunc}, ms...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowProgress", reflect.TypeOf((*MockFeIf)(nil).ShowProgress), varargs...)
}
